insert into Address (addressID, postalCode, streetName, city, country) values (1, '075064', 'Calypso', 'Iranduba', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (2, '555624', 'Hazelcrest', 'Lampari', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (3, '907715', 'Killdeer', 'Pokrovka', 'KG');
insert into Address (addressID, postalCode, streetName, city, country) values (4, '933570', 'Dawn', 'Omsk', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (5, '849550', 'Armistice', 'Tomaszów Mazowiecki', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (6, '793359', 'Karstens', 'Solo', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (7, '518186', 'Forest Run', 'Menzel Bourguiba', 'TN');
insert into Address (addressID, postalCode, streetName, city, country) values (8, '694607', 'Cascade', 'Neikeng', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (9, '995785', 'Grayhawk', 'Neiba', 'DO');
insert into Address (addressID, postalCode, streetName, city, country) values (10, '492366', 'Hanover', 'Hermosa', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (11, '338337', 'American Ash', 'Malesína', 'GR');
insert into Address (addressID, postalCode, streetName, city, country) values (12, '732428', 'Coleman', 'Yazd', 'IR');
insert into Address (addressID, postalCode, streetName, city, country) values (13, '680527', 'Oneill', 'Riangblolong', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (14, '892135', 'Melrose', 'Jiquilillo', 'NI');
insert into Address (addressID, postalCode, streetName, city, country) values (15, '613557', 'Continental', 'Poctol', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (16, '941021', 'Kedzie', 'Kurmuk', 'SD');
insert into Address (addressID, postalCode, streetName, city, country) values (17, '201838', 'Hoard', 'Dębica', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (18, '783330', 'Waxwing', 'Omigawa', 'JP');
insert into Address (addressID, postalCode, streetName, city, country) values (19, '305409', 'Anzinger', 'Bunisari', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (20, '547326', 'Macpherson', 'Ordzhonikidze', 'KZ');
insert into Address (addressID, postalCode, streetName, city, country) values (21, '357678', 'Namekagon', 'Kameda-honchō', 'JP');
insert into Address (addressID, postalCode, streetName, city, country) values (22, '831312', 'Dapin', 'Zheleznogorsk', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (23, '847731', 'Cardinal', 'Niedzica', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (24, '781905', 'Prairieview', 'Shengmi', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (25, '106853', 'Waywood', 'Al Matlīn', 'TN');
insert into Address (addressID, postalCode, streetName, city, country) values (26, '841110', 'New Castle', 'Independencia', 'PE');
insert into Address (addressID, postalCode, streetName, city, country) values (27, '462927', 'Sunnyside', 'Novhorodka', 'UA');
insert into Address (addressID, postalCode, streetName, city, country) values (28, '800689', 'Mitchell', 'Tecka', 'AR');
insert into Address (addressID, postalCode, streetName, city, country) values (29, '759185', 'Valley Edge', 'Yaozhou', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (30, '661655', 'Annamark', 'Rukunlima Bawah', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (31, '706504', 'South', 'Cabanaconde', 'PE');
insert into Address (addressID, postalCode, streetName, city, country) values (32, '878143', 'Caliangt', 'Narong', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (33, '127380', 'Chinook', 'José de Freitas', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (34, '786693', 'Ridgeview', 'Changhao', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (35, '020147', 'Manley', 'Rio Branco', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (36, '695108', 'Carberry', 'Virginia', 'ZA');
insert into Address (addressID, postalCode, streetName, city, country) values (37, '556380', 'Graedel', 'Kalkara', 'MT');
insert into Address (addressID, postalCode, streetName, city, country) values (38, '225998', 'Calypso', 'Yesan', 'KR');
insert into Address (addressID, postalCode, streetName, city, country) values (39, '205041', 'Butterfield', 'Gadingrejo', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (40, '331374', 'Morrow', 'Bykhaw', 'BY');
insert into Address (addressID, postalCode, streetName, city, country) values (41, '169583', 'Fuller', 'Geidam', 'NG');
insert into Address (addressID, postalCode, streetName, city, country) values (42, '579799', 'Lotheville', 'Gualaceo', 'EC');
insert into Address (addressID, postalCode, streetName, city, country) values (43, '921363', 'Continental', 'Changwon', 'KR');
insert into Address (addressID, postalCode, streetName, city, country) values (44, '192733', 'Oakridge', 'Pliska', 'BG');
insert into Address (addressID, postalCode, streetName, city, country) values (45, '557289', 'Killdeer', 'Chita', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (46, '923450', 'Oneill', 'Mamfe', 'CM');
insert into Address (addressID, postalCode, streetName, city, country) values (47, '469068', 'Kingsford', 'Hujia', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (48, '895017', 'Northridge', 'Morioka-shi', 'JP');
insert into Address (addressID, postalCode, streetName, city, country) values (49, '468874', 'Macpherson', 'Ordem', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (50, '253601', 'Granby', 'Böhöt', 'MN');
insert into Address (addressID, postalCode, streetName, city, country) values (51, '571872', 'Loeprich', 'Zhong’an', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (52, '313585', 'Dryden', 'Leipzig', 'DE');
insert into Address (addressID, postalCode, streetName, city, country) values (53, '258043', 'Ridge Oak', 'Berezne', 'UA');
insert into Address (addressID, postalCode, streetName, city, country) values (54, '267392', 'Lunder', 'Zhaxirabdain', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (55, '305340', 'Debs', 'Langkap', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (56, '673772', 'Nova', 'Sipe Sipe', 'BO');
insert into Address (addressID, postalCode, streetName, city, country) values (57, '571413', 'Bartelt', 'Dandian', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (58, '188214', 'Vahlen', 'Zhdanov', 'AM');
insert into Address (addressID, postalCode, streetName, city, country) values (59, '146765', 'Shopko', 'Ocumare de la Costa', 'VE');
insert into Address (addressID, postalCode, streetName, city, country) values (60, '934673', 'Clove', 'Dalaba', 'GN');
insert into Address (addressID, postalCode, streetName, city, country) values (61, '086731', 'Banding', 'Kourou', 'GF');
insert into Address (addressID, postalCode, streetName, city, country) values (62, '807069', 'Melrose', 'Amboise', 'FR');
insert into Address (addressID, postalCode, streetName, city, country) values (63, '885751', 'Derek', 'Placetas', 'CU');
insert into Address (addressID, postalCode, streetName, city, country) values (64, '614965', 'Weeping Birch', 'Świlcza', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (65, '138949', 'Goodland', 'Przeworsk', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (66, '092479', 'Shelley', 'Dagu', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (67, '098278', 'Springview', 'Marapat', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (68, '907050', 'Ridge Oak', 'Mosteiros', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (69, '846236', 'Granby', 'Nuwara Eliya', 'LK');
insert into Address (addressID, postalCode, streetName, city, country) values (70, '845894', 'Carey', 'Zhoushan', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (71, '443853', 'Starling', 'Orion', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (72, '375358', 'Fuller', 'Busia', 'KE');
insert into Address (addressID, postalCode, streetName, city, country) values (73, '355518', 'Upham', 'Ila Orangun', 'NG');
insert into Address (addressID, postalCode, streetName, city, country) values (74, '098964', 'Katie', 'Adelaide Mail Centre', 'AU');
insert into Address (addressID, postalCode, streetName, city, country) values (75, '116272', 'Dovetail', 'Norfolk County', 'CA');
insert into Address (addressID, postalCode, streetName, city, country) values (76, '318855', 'Forest', 'Maddarulug Norte', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (77, '576938', 'Messerschmidt', 'Khong Chai', 'TH');
insert into Address (addressID, postalCode, streetName, city, country) values (78, '810494', 'Stang', 'Kuishan', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (79, '265980', 'Gulseth', 'Krzykosy', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (80, '617351', 'Kim', 'Hougang', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (81, '404337', 'Manley', 'Xinglongquan', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (82, '991211', 'Toban', 'Oslo', 'NO');
insert into Address (addressID, postalCode, streetName, city, country) values (83, '834300', 'Hermina', 'Stalbe', 'LV');
insert into Address (addressID, postalCode, streetName, city, country) values (84, '751034', 'Graedel', 'Ōtsuki', 'JP');
insert into Address (addressID, postalCode, streetName, city, country) values (85, '156757', 'Ryan', 'Burūm', 'YE');
insert into Address (addressID, postalCode, streetName, city, country) values (86, '291237', 'Harbort', 'Cireundang', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (87, '529619', 'Clove', 'Kiangan', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (88, '464698', 'Gulseth', 'Goiana', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (89, '312812', 'Schlimgen', 'Armação de Búzios', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (90, '579502', 'Caliangt', 'Butubut Norte', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (91, '745158', 'Jay', 'Scottsdale', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (92, '717295', 'Florence', 'Ciburial', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (93, '825609', 'Chinook', 'Beaumont', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (94, '204072', 'Knutson', 'El Guapinol', 'HN');
insert into Address (addressID, postalCode, streetName, city, country) values (95, '713400', 'Mockingbird', 'Courbevoie', 'FR');
insert into Address (addressID, postalCode, streetName, city, country) values (96, '174655', 'Dahle', 'Wunat', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (97, '991771', 'Boyd', 'Nieuwegein', 'NL');
insert into Address (addressID, postalCode, streetName, city, country) values (98, '839896', 'Texas', 'Port Harcourt', 'NG');
insert into Address (addressID, postalCode, streetName, city, country) values (99, '727892', 'Sullivan', 'Salto', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (100, '097729', 'Chinook', 'Santol', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (101, '024320', 'East', 'Pudoc', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (102, '954132', 'Fremont', 'Khantaghy', 'KZ');
insert into Address (addressID, postalCode, streetName, city, country) values (103, '353625', 'Sunnyside', 'Bouaflé', 'CI');
insert into Address (addressID, postalCode, streetName, city, country) values (104, '118905', 'Russell', 'Dingshan', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (105, '283365', 'Hazelcrest', 'Ulashan', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (106, '469769', 'Maryland', 'Cimanggu', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (107, '404305', 'Katie', 'Marxog', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (108, '398154', 'Packers', 'Luchegorsk', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (109, '027724', 'Evergreen', 'Talacogon', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (110, '980223', 'Ryan', 'Qiting', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (111, '141409', 'Straubel', 'Ritaebang', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (112, '252239', 'Rieder', 'Tolomango', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (113, '401133', 'Lillian', 'Barra do Garças', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (114, '680324', 'Clarendon', 'Wushishi', 'NG');
insert into Address (addressID, postalCode, streetName, city, country) values (115, '366558', 'Mariners Cove', 'Negara', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (116, '944311', 'Superior', 'Straszyn', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (117, '345649', 'Bunker Hill', 'Walahir', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (118, '539710', 'Schurz', 'Jablah', 'SY');
insert into Address (addressID, postalCode, streetName, city, country) values (119, '305871', 'Green', 'Birātnagar', 'NP');
insert into Address (addressID, postalCode, streetName, city, country) values (120, '390359', 'Dovetail', 'Kedungwringin', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (121, '970626', 'Donald', 'Aliuroba', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (122, '075429', 'Cardinal', 'Campos Belos', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (123, '551284', 'Coolidge', 'Rawson', 'AR');
insert into Address (addressID, postalCode, streetName, city, country) values (124, '322603', 'Chinook', 'Batouri', 'CM');
insert into Address (addressID, postalCode, streetName, city, country) values (125, '410812', 'Express', 'Somerset East', 'ZA');
insert into Address (addressID, postalCode, streetName, city, country) values (126, '675304', 'Ruskin', 'Serowe', 'BW');
insert into Address (addressID, postalCode, streetName, city, country) values (127, '885622', 'Shopko', 'Harrisburg', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (128, '893258', 'Emmet', 'Kasimov', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (129, '184844', 'Kenwood', 'Comagascas', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (130, '458098', 'Straubel', 'Mâcon', 'FR');
insert into Address (addressID, postalCode, streetName, city, country) values (131, '045532', 'Susan', 'Lidingö', 'SE');
insert into Address (addressID, postalCode, streetName, city, country) values (132, '108140', 'Scofield', 'Palaiópyrgos', 'GR');
insert into Address (addressID, postalCode, streetName, city, country) values (133, '525367', 'Acker', 'Chaykovskaya', 'RU');
insert into Address (addressID, postalCode, streetName, city, country) values (134, '407410', 'Montana', 'Paris 02', 'FR');
insert into Address (addressID, postalCode, streetName, city, country) values (135, '586308', 'Nova', 'Semarang', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (136, '999962', 'Fair Oaks', 'Luoping', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (137, '373590', 'Wayridge', 'Souto', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (138, '421746', 'Homewood', 'Charleston', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (139, '721152', 'Longview', 'KwaMbonambi', 'ZA');
insert into Address (addressID, postalCode, streetName, city, country) values (140, '661885', 'John Wall', 'Binjiang', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (141, '112167', 'Vermont', 'Majalengka', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (142, '849508', 'Merrick', 'Mungwi', 'ZM');
insert into Address (addressID, postalCode, streetName, city, country) values (143, '761932', 'Village', 'Oqtosh', 'UZ');
insert into Address (addressID, postalCode, streetName, city, country) values (144, '294669', 'Hansons', 'Igarra', 'NG');
insert into Address (addressID, postalCode, streetName, city, country) values (145, '404385', 'Carpenter', 'Tonggu', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (146, '576716', 'Ohio', 'Rongxing', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (147, '034513', 'Sullivan', 'Hongqi', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (148, '942649', 'Gateway', 'San Diego', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (149, '485708', 'Hoard', 'Armavir', 'AM');
insert into Address (addressID, postalCode, streetName, city, country) values (150, '298708', 'Sutherland', 'Luis Donaldo Colosio', 'MX');
insert into Address (addressID, postalCode, streetName, city, country) values (151, '165870', 'Arizona', 'Moche', 'PE');
insert into Address (addressID, postalCode, streetName, city, country) values (152, '923288', 'Fair Oaks', 'Rosario', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (153, '122079', 'Esker', 'Sunjia Buzi', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (154, '259019', 'Arizona', 'Vargön', 'SE');
insert into Address (addressID, postalCode, streetName, city, country) values (155, '625474', 'Rockefeller', 'Włoszczowa', 'PL');
insert into Address (addressID, postalCode, streetName, city, country) values (156, '434470', 'Laurel', 'Las Vegas', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (157, '902126', 'Everett', 'Shizi', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (158, '524653', 'Homewood', 'Little Baguio', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (159, '620384', 'Bunker Hill', 'Baião', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (160, '722095', '2nd', 'Áno Kopanákion', 'GR');
insert into Address (addressID, postalCode, streetName, city, country) values (161, '632863', 'Hermina', 'Ayacucho', 'PE');
insert into Address (addressID, postalCode, streetName, city, country) values (162, '500997', 'Kinsman', 'Roldanillo', 'CO');
insert into Address (addressID, postalCode, streetName, city, country) values (163, '025117', 'Novick', 'Nangkapayung', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (164, '156357', 'Randy', 'Lameira', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (165, '976398', 'Springs', 'Sofiyivka', 'UA');
insert into Address (addressID, postalCode, streetName, city, country) values (166, '753216', 'Maywood', 'Winschoten', 'NL');
insert into Address (addressID, postalCode, streetName, city, country) values (167, '286543', '7th', 'Pantang', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (168, '422956', 'Veith', 'Luofang', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (169, '838962', 'Bartillon', 'Turkestan', 'KZ');
insert into Address (addressID, postalCode, streetName, city, country) values (170, '439089', 'Talisman', 'Labuhanjambu', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (171, '781963', 'Leroy', 'Nanmu', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (172, '187880', 'Waxwing', 'Xishiqiao', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (173, '731746', 'Hintze', 'Lauro de Freitas', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (174, '949288', 'Lakeland', 'Sélestat', 'FR');
insert into Address (addressID, postalCode, streetName, city, country) values (175, '590149', 'Harbort', 'Dongtucheng', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (176, '753271', 'Tennessee', 'Sumberejo', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (177, '765920', 'Thackeray', 'Anchorage', 'US');
insert into Address (addressID, postalCode, streetName, city, country) values (178, '141755', 'Sunnyside', 'Hayan Hudong', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (179, '788231', 'Utah', 'Moita da Roda', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (180, '975566', 'Stephen', 'Fuji', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (181, '981262', 'Atwood', 'Kalianyar Selatan', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (182, '210024', 'Kingsford', 'San Pablo', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (183, '688555', 'Lindbergh', 'Åby', 'SE');
insert into Address (addressID, postalCode, streetName, city, country) values (184, '753407', 'Muir', 'Itajaí', 'BR');
insert into Address (addressID, postalCode, streetName, city, country) values (185, '261170', 'Hoepker', 'Vilar do Monte', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (186, '529540', 'Shasta', 'Old Harbour Bay', 'JM');
insert into Address (addressID, postalCode, streetName, city, country) values (187, '651336', 'Cherokee', 'Chedao', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (188, '080987', 'Montana', 'Tignoan', 'PH');
insert into Address (addressID, postalCode, streetName, city, country) values (189, '659318', 'Brickson Park', 'Longchi', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (190, '732193', 'American Ash', 'Al Ghuwayrīyah', 'QA');
insert into Address (addressID, postalCode, streetName, city, country) values (191, '019821', 'Blue Bill Park', 'Zumiao', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (192, '330869', 'Merry', 'Rio de Moinhos', 'PT');
insert into Address (addressID, postalCode, streetName, city, country) values (193, '990149', 'Roxbury', 'Misasi', 'TZ');
insert into Address (addressID, postalCode, streetName, city, country) values (194, '145223', '7th', 'Amfíkleia', 'GR');
insert into Address (addressID, postalCode, streetName, city, country) values (195, '226681', 'Forster', 'Wanying', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (196, '341942', 'Amoth', 'Gandajika', 'CD');
insert into Address (addressID, postalCode, streetName, city, country) values (197, '881666', 'Banding', 'Nanxiang', 'CN');
insert into Address (addressID, postalCode, streetName, city, country) values (198, '690941', 'Thierer', 'Kushovë', 'AL');
insert into Address (addressID, postalCode, streetName, city, country) values (199, '977184', 'Laurel', 'Atawutung', 'ID');
insert into Address (addressID, postalCode, streetName, city, country) values (200, '959704', 'Mariners Cove', 'Aigínio', 'GR');
